# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo',
            field=models.TextField(verbose_name='Aluno'),
        ),
    ]
