# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0002_auto_20180809_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='tipo',
            field=models.TextField(default='Professor'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='tipo',
            field=models.TextField(default='Tecnico'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='tipo',
            field=models.TextField(default='Aluno'),
        ),
    ]
