# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0002_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='tag',
            field=models.TextField(),
        ),
    ]
