# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0003_auto_20171013_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('nome',)},
        ),
    ]
