# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0004_auto_20171013_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.IntegerField()),
                ('tag', models.TextField()),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
