# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-03 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0008_aluno_professor_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('cpf', models.IntegerField()),
                ('tag', models.TextField()),
                ('tipo', models.CharField(choices=[('dirigente', 'Dirigente'), ('secretario', 'Secretario')], default='dirigente', max_length=50, verbose_name='Função')),
            ],
            options={
                'ordering': ('tipo', 'nome'),
            },
        ),
    ]
