# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0009_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('dirigente', 'Dirigente'), ('secretario', 'Secretario'), ('tesoureiro', 'Tesoureiro')], default='dirigente', max_length=50, verbose_name='Função'),
        ),
    ]
