# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_access', '0010_auto_20180308_0812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tecnico',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='professor_responsavel',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('professor', 'Professor'), ('tecnico', 'Tecnico')], default='professor', max_length=50, verbose_name='Função'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
